src/Entity/Coach.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CoachRepository")
 */
class Coach
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Session", mappedBy="coaches")
     */
    private $sessions;

    public function __construct()
    {
        $this->sessions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection|Session[]
     */
    public function getSessions(): Collection
    {
        return $this->sessions;
    }

    public function addSession(Session $session): self
    {
        if (!$this->sessions->contains($session)) {
            $this->sessions[] = $session;
            $session->addCoach($this);
        }

        return $this;
    }

    public function removeSession(Session $session): self
    {
        if ($this->sessions->contains($session)) {
            $this->sessions->removeElement($session);
            $session->removeCoach($this);
        }

        return $this;
    }


    public function getPunchesCount() {
        return array_reduce($this->sessions->toArray(), function($carry, Session $item) {
            return $carry + $item->getPunchesCount();
        });
    }

    public function getAverageVelocity() {
        $velocities = array_reduce($this->sessions->toArray(), function($carry, Session $item) {
            return $carry + $item->getAverageVelocity();
        });
        return $velocities / $this->sessions->count();
    }

    public function getAverageIntensity() {
        $intensities = array_reduce($this->sessions->toArray(), function($carry, Session $item) {
            return $carry + $item->getIntensity();
        });
        return $intensities / $this->sessions->count();
    }


    public function getCountDetail() {
        $count = [
            Punch::HAND_LEFT => [
                Punch::TYPE_DIRECT => 0,
                Punch::TYPE_POWER => 0,
            ],
            Punch::HAND_RIGHT => [
                Punch::TYPE_DIRECT => 0,
                Punch::TYPE_POWER => 0,
            ]
        ];
        /** @var Session $session */
        foreach ($this->sessions as $session) {
            $countDetail = $session->getCountDetail();

            foreach ($countDetail as $hand => $types) {
                foreach ($types as $type => $nb) {
                    $count[$hand][$type] += $nb;
                }
            }
        }
        return $count;
    }

    public function getAverageVelocityDetail() {
        $velocities = [
            Punch::HAND_LEFT => [
                Punch::TYPE_DIRECT => 0,
                Punch::TYPE_POWER => 0,
            ],
            Punch::HAND_RIGHT => [
                Punch::TYPE_DIRECT => 0,
                Punch::TYPE_POWER => 0,
            ]
        ];
        if ($this->sessions->isEmpty())
            return $velocities;

        /** @var Session $session */
        foreach ($this->sessions as $session) {
            $detailSession = $session->getAverageVelocityDetail();
            foreach ($detailSession as $hand => $types) {
                foreach ($types as $type => $velo) {
                    $velocities[$hand][$type] += $velo;
                }
            }
        }
        foreach ($velocities as $hand => $types) {
            foreach ($types as $type => $velo) {
                $velocities[$hand][$type] /= $this->sessions->count();
            }
        }
        return $velocities;
    }
}

src/Controller/DefaultController.php
<?php

namespace App\Controller;

use App\Repository\CoachRepository;
use App\Repository\SessionRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class DefaultController extends AbstractController
{
    /** @var SessionRepository */
    private $sessionRepository;

    /** @var CoachRepository  */
    private $coachRepository;

    /**
     * DefaultController constructor.
     * @param SessionRepository $sessionRepository
     */
    public function __construct(SessionRepository $sessionRepository, CoachRepository $coachRepository)
    {
        $this->sessionRepository = $sessionRepository;
        $this->coachRepository = $coachRepository;
    }


    /**
     * @Route("/default", name="default")
     */
    public function index()
    {

        $sessions = $this->sessionRepository->findAll();
        $coaches = $this->coachRepository->findAll();
        return $this->render('default/index.html.twig', [
            "sessions" => $sessions,
            "coaches" => $coaches
        ]);
    }
}

templates/default/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello DefaultController!{% endblock %}

{% block body %}

    <h1>MMA Camp Stats</h1>
    <div class="page">
        <div class="titles">

            <span class="title">COACH</span>
            <span class="title">Sessions</span>
            <span class="title" data-type="punches">Punches</span>
            <span class="title" data-type="punches-session">Punches <span class="little">/ session</span></span>
            <span class="title" data-type="velocity">Average punch velocity</span>
            <span class="title">Average session intensity</span>

        </div>
        <div class="coaches">

            {% for coach in coaches %}
                <div class="coach">
                    <div class="identity">
                        <img src="/images/coaches/{{ coach.name|lower }}.png">
                        <span class="name"> {{ coach.name }}</span>
                    </div>
                    <span class="value">
                        {{ coach.sessions|length }}
                    </span>
                    <span class="value" data-type="punches">
                        {{ coach.punchesCount|number_format(0,'.', ' ') }}

                        {% set detail = coach.countDetail %}
                        <table>
                            <tr>
                                <td>{{ detail["Left"]["Straight"]|number_format(0,'.', ' ')  }}</td>
                                <td>{{ detail["Right"]["Straight"]|number_format(0,'.', ' ')  }}</td>
                            </tr>
                            <tr>
                                <td>{{ detail["Left"]["Power"]|number_format(0,'.', ' ')  }}</td>
                                <td>{{ detail["Right"]["Power"]|number_format(0,'.', ' ')  }}</td>
                            </tr>
                        </table>
                    </span>
                    <span class="value" data-type="punches-session">
                        {{ (coach.punchesCount / coach.sessions|length)|number_format(0) }}
                         <table>
                            <tr>
                                <td>{{ (detail["Left"]["Straight"] / coach.sessions|length)|number_format(0) }}</td>
                                <td>{{ (detail["Right"]["Straight"] / coach.sessions|length)|number_format(0) }}</td>
                            </tr>
                            <tr>
                                <td>{{ (detail["Left"]["Power"] / coach.sessions|length)|number_format(0) }}</td>
                                <td>{{ (detail["Right"]["Power"] / coach.sessions|length)|number_format(0) }}</td>
                            </tr>
                        </table>
                    </span>
                    <span class="value" data-type="velocity">
                        {{ coach.averageVelocity|number_format(2,'.', ' ') }} km/h

                         {% set velocities = coach.averageVelocityDetail %}
                        <table>
                            <tr>
                                <td>{{ velocities["Left"]["Straight"]|number_format(2,'.', ' ') }} km/h</td>
                                <td>{{ velocities["Right"]["Straight"] |number_format(2,'.', ' ') }} km/h</td>
                            </tr>
                            <tr>
                                <td>{{ velocities["Left"]["Power"]|number_format(2,'.', ' ') }} km/h</td>
                                <td>{{ velocities["Right"]["Power"]|number_format(2,'.', ' ') }} km/h</td>
                            </tr>
                        </table>
                    </span>
                    <span class="value">
                        {{ (coach.averageIntensity/1000)|number_format(2) }}k
                    </span>
                </div>
            {% endfor %}
        </div>
    </div>


    <table>
        <tr>
            <td>Jab</td>
            <td>Cross</td>
        </tr>
        <tr>
            <td>Crochet/uppercut avant</td>
            <td>Crochet/uppercut arrière</td>
        </tr>
    </table>
{% endblock %}